### Register

POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "john.brown@example.com",
  "firstName": "John",
  "lastName": "Brown",
  "password": "password01"
}


### signin

POST http://localhost:7000/auth/signin
Content-Type: application/json

{
  "email": "john.brown@example.com",
  "password": "password01"
}


### Protected Movies

GET http://localhost:7000/movies
Content-Type : application/json
Cookie: connect.sid=s%3A_D-lYV7Y0MMykUymcNOv5iJIRybYLXUP.%2BM5H5TDXajHAosvgxaT0%2FLictwCYnDu4fowmuG0DLzg;
